{{- if .Values.masterSecret.create }}
apiVersion: {{ .Values.masterSecret.sealedApiVersion }}
kind: SealedSecret
metadata:
  name: {{ .Values.masterSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
spec:
  encryptedData:
    username: {{ required "masterSecret.encryptedUsername is required when masterSecret.create=true" .Values.masterSecret.encryptedUsername | quote }}
    password: {{ required "masterSecret.encryptedPassword is required when masterSecret.create=true" .Values.masterSecret.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.masterSecret.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "postgres-operator.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
